# Generated by Django 4.1.12 on 2023-10-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemetadata',
            name='file',
        ),
    ]
