# Generated by Django 4.1.12 on 2023-10-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_controller', '0002_remove_filemetadata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='modified_file',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='operations',
            field=models.JSONField(default=list),
        ),
    ]
