# Generated by Django 4.1.12 on 2024-01-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_controller', '0003_filemetadata_modified_file_filemetadata_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='edited_file',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='cloudinary_url',
            field=models.URLField(null=True),
        ),
    ]
