# Generated by Django 4.2.6 on 2023-10-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='code',
        ),
    ]
